# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md
name: PhotoSync
options:
  bundleIdPrefix: org.movieos
packages:
  SwiftyDropbox:
    url: https://github.com/dropbox/SwiftyDropbox.git
    exactVersion: 10.0.0-beta.3

targets:
  PhotoSync:
    name: PhotoSync
    type: application
    platform: iOS
    deploymentTarget: "26.1"
    scheme:
      testTargets:
        - PhotoSyncTests
    settings:
      base:
        TARGETED_DEVICE_FAMILY: "1,2" # iPhone and iPad
        PRODUCT_BUNDLE_IDENTIFIER: org.movieos.photosync
        DEVELOPMENT_TEAM: 76AFK3W7M9
        SUPPORTS_MACCATALYST: YES
      debug:
      release:
    sources:
      - path: "PhotoSync"
        name: "Code"
        type: syncedFolder
      - path: "README.md"
        buildPhase: none
      - path: "CHANGELOG.md"
        buildPhase: none
      - path: "project.yml"
        buildPhase: none
      - path: ".swiftlint.yml"
        buildPhase: none
      - path: "Info.plist"
        buildPhase: none
    dependencies:
      - package: SwiftyDropbox
    info:
      path: Info.plist
      properties:
        NSPhotoLibraryUsageDescription: "The app reads your photos to send them to Dropbox"
        LSApplicationCategoryType: public.app-category.developer-tools
        UILaunchScreen:
          UIColorName: LaunchBackground
          UIImageName: AppIcon
        CFBundleShortVersionString: "1"
        CFBundleVersion: "1.0"
        ITSAppUsesNonExemptEncryption: false
        UIStatusBarStyle: UIStatusBarStyleLightContent
        UIViewControllerBasedStatusBarAppearance: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        LSApplicationQueriesSchemes:
          - dbapi-8-emm
          - dbapi-2
        CFBundleURLTypes:
          - CFBundleURLName: ""
            CFBundleURLSchemes:
              - db-ru820t3myp7s6vk
    entitlements:
      path: PhotoSync.entitlements
      properties:
        keychain-access-groups: []
    postCompileScripts:
      - script: /opt/homebrew/bin/swiftlint
        name: Run SwiftLint
        basedOnDependencyAnalysis: false

  PhotoSyncTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "26.1"
    sources:
      - path: "PhotoSyncTests"
        type: syncedFolder
    dependencies:
      - target: PhotoSync
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.movieos.photosync.tests
        GENERATE_INFOPLIST_FILE: YES
