# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md
name: PhotoSync
options:
  bundleIdPrefix: org.movieos
packages:
  SwiftyDropbox:
    url: https://github.com/dropbox/SwiftyDropbox.git
    exactVersion: 10.0.0-beta.3
  KeychainSwift:
    url: https://github.com/evgenyneu/keychain-swift.git
    revision: 32a99b537d1c6f3529a08257c28a5feb70c0c5af
  CollectionConcurrencyKit:
    url: https://github.com/JohnSundell/CollectionConcurrencyKit.git
    revision: b4f23e24b5a1bff301efc5e70871083ca029ff95

targets:
  PhotoSync:
    name: PhotoSync
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    scheme: {}
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1 # iphone only
        PRODUCT_BUNDLE_IDENTIFIER: org.movieos.photosync
        DEVELOPMENT_TEAM: 76AFK3W7M9
        SUPPORTS_MACCATALYST: YES
      debug:
      release:
    sources:
      - path: "PhotoSync"
        name: "Code"
      - path: "README.md"
        buildPhase: none
      - path: "CHANGELOG.md"
        buildPhase: none
      - path: "project.yml"
        buildPhase: none
      - path: ".swiftlint.yml"
        buildPhase: none
      - path: "Info.plist"
        buildPhase: none
    dependencies:
      - package: SwiftyDropbox
      - package: KeychainSwift
      - package: CollectionConcurrencyKit
    info:
      path: Info.plist
      properties:
        NSPhotoLibraryUsageDescription: "The app reads your photos to send them to Dropbox"
        LSApplicationCategoryType: public.app-category.developer-tools
        UILaunchScreen:
          UIColorName: LaunchBackground
          UIImageName: AppIcon
        CFBundleShortVersionString: "1"
        CFBundleVersion: "1.0"
        ITSAppUsesNonExemptEncryption: false
        UIStatusBarStyle: UIStatusBarStyleLightContent
        UIViewControllerBasedStatusBarAppearance: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        LSApplicationQueriesSchemes:
          - dbapi-8-emm
          - dbapi-2
        CFBundleURLTypes:
          - CFBundleURLName: ""
            CFBundleURLSchemes:
              - db-ru820t3myp7s6vk
    entitlements:
      path: PhotoSync.entitlements
      properties:
        keychain-access-groups: []
    postCompileScripts:
      - script: /opt/homebrew/bin/swiftlint
        name: Run SwiftLint
        basedOnDependencyAnalysis: false
